name = "Measurements"
uuid = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
authors = ["Mosè Giordano <mose@gnu.org>"]
version = "2.1.1"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Calculus = "≥ 0.4.1"
QuadGK = "≥ 2.0.1"
RecipesBase = "≥ 0.6.0"
Requires = "≥ 0.5.0"
SpecialFunctions = "≥ 0.7.0"
julia = "≥ 1.0.0"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["QuadGK", "SpecialFunctions", "Statistics", "Test", "Unitful"]
