[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Documenter = "~0.20"
